[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
{% if platform == "Liveview" %}
dioxus = { version = "0.4" }
tokio = { version = "1.27.0", features = ["full"] }
{% if backend == "Axum" %}
dioxus-liveview = { version = "0.4", features = ["axum"] }
axum = { version = "0.6.12", features = ["ws"] }
{% endif %}
{% if backend == "Salvo" %}
dioxus-liveview = { version = "0.4", features = ["salvo"] }
salvo = { version = "0.37.9", features = ["ws"] }
{% endif %}
{% if backend == "Warp" %}
dioxus-liveview = { version = "0.4", features = ["warp"] }
warp = { version = "0.3.3" }
{% endif %}
{% endif %}
{% if platform == "web" %}
dioxus-web = { version = "0.4" }
dioxus = { version = "0.4" }
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
{% endif %}
{% if platform == "desktop" %}
dioxus-desktop = { version = "0.4" }
dioxus = { version = "0.4" }
{% endif %}
{% if platform == "TUI" %}
dioxus-tui = { version = "0.4" }
dioxus = { version = "0.4" }
{% endif %}
{% if platform == "Fullstack" %}
{% if router %}
dioxus-fullstack = { version = "0.4", features = ["router"] }
{% else %}
dioxus-fullstack = { version = "0.4" }
{% endif %}
dioxus = { version = "0.4" }
dioxus-web = { version = "0.4", features = ["hydrate"], optional = true }
tokio = { version = "1.27.0", features = ["full"], optional = true }
serde = "1.0.159"
{% if backend == "Axum" %}
axum = { version = "0.6.12", optional = true }
{% endif %}
{% if backend == "Salvo" %}
salvo = { version = "0.37.9", optional = true }
{% endif %}
{% if backend == "Warp" %}
warp = { version = "0.3.3", optional = true }
{% endif %}
{% endif %}
{% if router %}
{% if platform == "web" %}
dioxus-router = { version = "0.4", features = ["web"] }
{% else %}
dioxus-router = { version = "0.4" }
{% endif %}
{% endif %}

log = "0.4.6"

{% if platform == "Fullstack" %}
[features]
default = []
{% if backend == "Axum" %}
ssr = ["axum", "tokio", "dioxus-fullstack/axum"]
{% endif %}
{% if backend == "Salvo" %}
ssr = ["salvo", "tokio", "dioxus-fullstack/salvo"]
{% endif %}
{% if backend == "Warp" %}
ssr = ["warp", "tokio", "dioxus-fullstack/warp"]
{% endif %}
{% if router %}
web = ["dioxus-web", "dioxus-router/web"]
{% else %}
web = ["dioxus-web"]
{% endif %}
{% endif %}
